apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmb
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vmb
  template:
    metadata:
      labels:
        app: vmb
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: controller
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash", "/scripts/controller.sh"]
        volumeMounts:
        - name: script
          mountPath: /scripts
      volumes:
      - name: script
        configMap:
          name: vmb-script
          defaultMode: 0755
