apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-j-dv
  namespace: ubuntu-ns
spec:
  source:
    pvc:
      namespace: ubuntu-ns
      name: ubuntu-j-dv
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 21Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-j-datadisk-1
  namespace: ubuntu-ns
spec:
  source:
    pvc:
      namespace: ubuntu-ns
      name: ubuntu-j-datadisk-1
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 21Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-j-datadisk-2
  namespace: ubuntu-ns
spec:
  source:
    pvc:
      namespace: ubuntu-ns
      name: ubuntu-j-datadisk-2
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 21Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-j-vm
  namespace: ubuntu-ns
spec:
  running: false
  template:
    metadata:
      annotations:
        kubevirt.io/pci-topology-version: v3
      creationTimestamp: null
      labels:
        vm-hostname: ubuntu-j-host
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - cache: writethrough
            disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          - disk:
              bus: virtio
            name: datadisk-1
          - disk:
              bus: virtio
            name: datadisk-2
        firmware:
          serial: 814f10fa-b7e8-485f-8f81-ae2ecade0208
          uuid: b3a4e907-1750-4a34-8e6f-42c3ddf5c38d
        machine:
          type: q35
        resources:
          requests:
            memory: 4Gi
      volumes:
      - dataVolume:
          name: ubuntu-j-dv
        name: rootdisk
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            users:
              - name: jiya
                sudo: ALL=(ALL) NOPASSWD:ALL
                shell: /bin/bash
                ssh_authorized_keys:
                  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFnt6ZBwBUW0F/hPffkHDgPIy+4JnR6ZFfrQLqpBXx0G jiya@DESKTOP-FEUJGCU"
            chpasswd:
              list: |
                jiya:jiya123
              expire: false
            runcmd:
              - sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
              - sed -i 's/^ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/' /etc/ssh/sshd_config
        name: cloudinitdisk
      - dataVolume:
          name: ubuntu-j-datadisk-1
        name: datadisk-1
      - dataVolume:
          name: ubuntu-j-datadisk-2
        name: datadisk-2
